version: '3'

services:
  db:
    image: postgres
    command:
      - postgres
      - -c
      - max_connections=300
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pg-db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

